name: tests
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests with Maven
        run: mvn -B test --file pom.xml

      - name: Merge PR if tests pass
        if: ${{ github.event_name == 'pull_request' && success() }}
        uses: peter-evans/merge-pull-request@v2
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash # 你可以选择 'merge', 'squash', 或 'rebase'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
